### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by simplextech** [frankdice/tappecue-api#5]
Currently reviewing the API with Postman and when trying to do the basic login I receive the following:

`{
    "message": "Missing loging information"
}`

**Comment by frankdice** [comment]
That error means the server isn't seeing the username/password POST parameters. Do you have any way to review what parameters your software is sending? The login method doesn't require any extra headers, and is just a generic POST with two parameters to acquire the auth token (which will need to be passed as an http header).

Also, you can test the login method using the curl command from a linux/mac host:
`curl -d "username=test&password=testpass" https://tappecue.babyvelociraptor.com/login`

**Comment by simplextech** [comment]
I found the issue and perhaps it could be a validation check added for it.

I’m working with another person (their tappecue) on developing this plugin and they provided the credential information.  What was provided was their e-mail address.  Doing the same test with curl presented the same error.  So just to try I removed the last portion of their email the @domain and it authenticated without error.

Regards,

John Eubanks
Simplex Technology



Website:  http://www.simplextech.net
E-Mail:  jeubanks@simplextech.net

**Comment by frankdice** [comment]
Hi John,

That makes sense, I think this could merit a documentation update at a minimum. When registering a Tappecue account, customers provide:
-Email
-Username
-Password

The Username and Password are used to login to the Tappecue mobile app (and the API since it's a passthrough), and the email isn't used directly unless there's a password reset.

In this case, the credentials provided by the other person, their username happened to line up with their email (my account does not).

**Comment by simplextech** [comment]
Just one of those things when working with other users 😊

I agree a documentation note would probably be useful.

Regards,

John Eubanks
Simplex Technology



Website:  http://www.simplextech.net
E-Mail:  jeubanks@simplextech.net

**Comment by frankdice** [comment]
This has been resolved, email addresses are now allowed for login via the API.
